export class CampeoesUtil {
    public static campeoes: any[] = [
        {nome: 'Aatrox', imagem: '../../assets/opcoesCampeoes/Aatrox_Render.png', value: 1},
        {nome: 'Ahri', imagem: '../../assets/opcoesCampeoes/Ahri_Render.png', value: 2},
        {nome: 'Akali', imagem: '../../assets/opcoesCampeoes/Akali_Render.png', value: 3},
        {nome: 'Alistar', imagem: '../../assets/opcoesCampeoes/Alistar_Render.png', value: 4},
        {nome: 'Amumu', imagem: '../../assets/opcoesCampeoes/Amumu_Render.png', value: 5},
        {nome: 'Anivia', imagem: '../../assets/opcoesCampeoes/Anivia_Render.png', value: 6},
        {nome: 'Annie', imagem: '../../assets/opcoesCampeoes/Annie_Render.png', value: 7},
        {nome: 'Ashe', imagem: '../../assets/opcoesCampeoes/Ashe_Render.png', value: 8},
        {nome: 'Aurelion Sol', imagem: '../../assets/opcoesCampeoes/Aurelion_Sol_Render.png', value: 9},
        {nome: 'Azir', imagem: '../../assets/opcoesCampeoes/Azir_Render.png', value: 10},
        {nome: 'Bardo', imagem: '../../assets/opcoesCampeoes/Bard_Render.png', value: 11},
        {nome: 'Blitzcranck', imagem: '../../assets/opcoesCampeoes/Blitzcrank_Render.png', value: 12},
        {nome: 'Brand', imagem: '../../assets/opcoesCampeoes/Brand_Render.png', value: 13},
        {nome: 'Braum', imagem: '../../assets/opcoesCampeoes/Braum_Render.png', value: 14},
        {nome: 'Caitlyn', imagem: '../../assets/opcoesCampeoes//Caitlyn_Render.png', value: 15},
        {nome: 'Camille', imagem: '../../assets/opcoesCampeoes/Camille_Render.png', value: 16},
        {nome: 'Cassiopeia', imagem: '../../assets/opcoesCampeoes/Cassiopeia_Render.png', value: 17},
        {nome: "Cho'Gath", imagem: '../../assets/opcoesCampeoes/Cho_Gath_Render.png', value: 18},
        {nome: 'Corki', imagem: '../../assets/opcoesCampeoes/Corki_Render.png', value: 19},
        {nome: 'Darius', imagem: '../../assets/opcoesCampeoes/Darius_Render.png', value: 20},
        {nome: 'Diana', imagem: '../../assets/opcoesCampeoes/Diana_Render.png', value: 21},
        {nome: 'Dr. Mundo', imagem: '../../assets/opcoesCampeoes/Dr._Mundo_Render.png', value: 22},
        {nome: 'Draven', imagem: '../../assets/opcoesCampeoes/Draven_Render.png', value: 23},
        {nome: 'Ekko', imagem: '../../assets/opcoesCampeoes/Ekko_Render.png', value: 24},
        {nome: 'Elise', imagem: '../../assets/opcoesCampeoes/Elise_Render.png', value: 25},
        {nome: 'Evelynn', imagem: '../../assets/opcoesCampeoes/Evelynn_Render.png', value: 26},
        {nome: 'Ezreal', imagem: '../../assets/opcoesCampeoes/Ezreal_Render.png', value: 27},
        {nome: 'Fiddlesticks', imagem: '../../assets/opcoesCampeoes/Fiddlesticks_Render.png', value: 28},
        {nome: 'Fiora', imagem: '../../assets/opcoesCampeoes/Fiora_Render.png', value: 29},
        {nome: 'Fizz', imagem: '../../assets/opcoesCampeoes/Fizz_Render.png', value: 30},
        {nome: 'Galio', imagem: '../../assets/opcoesCampeoes/Galio_Render.png', value: 31},
        {nome: 'Gangplank', imagem: '../../assets/opcoesCampeoes/Gangplank_Render.png', value: 32},
        {nome: 'Garen', imagem: '../../assets/opcoesCampeoes/Garen_Render.png', value: 33},
        {nome: 'Gnar', imagem: '../../assets/opcoesCampeoes/Gnar_Render.png', value: 34},
        {nome: 'Gragas', imagem: '../../assets/opcoesCampeoes/Gragas_Render.png', value: 35},
        {nome: 'Graves', imagem: '../../assets/opcoesCampeoes/Graves_Render.png', value: 36},
        {nome: 'Hecarim', imagem: '../../assets/opcoesCampeoes/Hecarim_Render.png', value: 37},
        {nome: 'Heimerdinger', imagem: '../../assets/opcoesCampeoes/Heimerdinger_Render.png', value: 38},
        {nome: 'Illaoi', imagem: '../../assets/opcoesCampeoes/Illaoi_Render.png', value: 39},
        {nome: 'Irelia', imagem: '../../assets/opcoesCampeoes/Irelia_Render.png', value: 40},
        {nome: 'Ivern', imagem: '../../assets/opcoesCampeoes/Ivern_Render.png', value: 41},
        {nome: 'Janna', imagem: '../../assets/opcoesCampeoes/Janna_Render.png', value: 42},
        {nome: 'Jarvan IV', imagem: '../../assets/opcoesCampeoes/Jarvan_IV_Render.png', value: 43},
        {nome: 'Jax', imagem: '../../assets/opcoesCampeoes/Jax_Render.png', value: 44},
        {nome: 'Jayce', imagem: '../../assets/opcoesCampeoes/Jayce_Render.png', value: 45},
        {nome: 'Jhin', imagem: '../../assets/opcoesCampeoes/', value: 46},
        {nome: 'Jinx', imagem: '../../assets/opcoesCampeoes/Jinx_Render.png', value: 47},
        {nome: "kai'sa", imagem: '../../assets/opcoesCampeoes/Kai’Sa_Render.png', value: 48},
        {nome: 'Kalista', imagem: '../../assets/opcoesCampeoes/Kalista_Render.png', value: 49},
        {nome: 'Karma', imagem: '../../assets/opcoesCampeoes/Karma_Render.png', value: 50},
        {nome: 'Karthus', imagem: '../../assets/opcoesCampeoes/Karthus_Render.png', value: 51},
        {nome: 'Kassadin', imagem: '../../assets/opcoesCampeoes/Kassadin_Render.png', value: 52},
        {nome: 'Katarina', imagem: '../../assets/opcoesCampeoes/Katarina_Render.png', value: 53},
        {nome: 'Kayle', imagem: '../../assets/opcoesCampeoes/Kayle_Zealous_Render.png', value: 54},
        {nome: 'Kennen', imagem: '../../assets/opcoesCampeoes/Kennen_Render.png', value: 55},
        {nome: "Kha'Zix", imagem: '../../assets/opcoesCampeoes/Kha%27Zix_Render.png', value: 56},
        {nome: 'Kindred', imagem: '../../assets/opcoesCampeoes/Kindred_Render.png', value: 57},
        {nome: 'Kled', imagem: '../../assets/opcoesCampeoes/Kled_render.png', value: 58},
        {nome: "Kog'Maw", imagem: '../../assets/opcoesCampeoes/Kog%27Maw_Render.png', value: 59},
        {nome: 'LeBlanc', imagem: '../../assets/opcoesCampeoes/LeBlanc_Render.png', value: 60},
        {nome: 'Lee Sin', imagem: '../../assets/opcoesCampeoes/Lee_Sin_Render.png', value: 61},
        {nome: 'Leona', imagem: '../../assets/opcoesCampeoes/Leona_Render.png', value: 62},
        {nome: 'Lissandra', imagem: '../../assets/opcoesCampeoes/Lissandra_Render.png', value: 63},
        {nome: 'Lucian', imagem: '../../assets/opcoesCampeoes/Lucian_Render.png', value: 64},
        {nome: 'Lulu', imagem: '../../assets/opcoesCampeoes/Lulu_Render.png', value: 65},
        {nome: 'Lux', imagem: '../../assets/opcoesCampeoes/Lux_Render.png', value: 66},
        {nome: 'Maplhite', imagem: '../../assets/opcoesCampeoes/Malphite_Render.png', value: 67},
        {nome: 'Malzahar', imagem: '../../assets/opcoesCampeoes/Malzahar_Render.png', value: 68},
        {nome: 'Maokai', imagem: '../../assets/opcoesCampeoes/Maokai_Render.png', value: 69},
        {nome: 'Master Yi', imagem: '../../assets/opcoesCampeoes/Master_Yi_Render.png', value: 70},
        {nome: 'Miss Fortune', imagem: '../../assets/opcoesCampeoes/Miss_Fortune_Render.png', value: 71},
        {nome: 'Mordekaiser', imagem: '../../assets/opcoesCampeoes/Mordekaiser_Render.png', value: 72},
        {nome: 'Morgana', imagem: '../../assets/opcoesCampeoes/Morgana_Render.png', value: 73},
        {nome: 'Nami', imagem: '../../assets/opcoesCampeoes/Nami_Render.png', value: 74},
        {nome: 'Nasus', imagem: '../../assets/opcoesCampeoes/Nasus_Render.png', value: 75},
        {nome: 'Nautilus', imagem: '../../assets/opcoesCampeoes/Nautilus_Render.png', value: 76},
        {nome: 'Neeko', imagem: '../../assets/opcoesCampeoes/Neeko_Render.png', value: 77},
        {nome: 'Nidalee', imagem: '../../assets/opcoesCampeoes/Nidalee_Render.png', value: 78},
        {nome: 'Nocturne', imagem: '../../assets/opcoesCampeoes/Nocturne_Render.png', value: 79},
        {nome: 'Nunu', imagem: '../../assets/opcoesCampeoes/Nunu_Render.png', value: 80},
        {nome: 'Olaf', imagem: '../../assets/opcoesCampeoes/Olaf_Render.png', value: 81},
        {nome: 'Orianna', imagem: '../../assets/opcoesCampeoes/Orianna_Render.png', value: 82},
        {nome: 'Ornn', imagem: '../../assets/opcoesCampeoes/Ornn_Render.png', value: 83},
        {nome: 'Pantheon', imagem: '../../assets/opcoesCampeoes/Pantheon_Render.png', value: 84},
        {nome: 'Poppy', imagem: '../../assets/opcoesCampeoes/Poppy_Render.png', value: 85},
        {nome: 'Pyke', imagem: '../../assets/opcoesCampeoes/Pyke_Render.png', value: 86},
        {nome: 'Qiyana', imagem: '../../assets/opcoesCampeoes/Qiyana_Render.png', value: 87},
        {nome: 'Quinn', imagem: '../../assets/opcoesCampeoes/Quinn_Render.png', value: 88},
        {nome: 'Rakan', imagem: '../../assets/opcoesCampeoes/Rakan_Render.png', value: 89},
        {nome: 'Rammus', imagem: '../../assets/opcoesCampeoes/Rammus_Render.png', value: 90},
        {nome: "Rek'Sai", imagem: '../../assets/opcoesCampeoes/Rek%27Sai_Render.png', value: 91},
        {nome: 'Renekton', imagem: '../../assets/opcoesCampeoes/Renekton_Render.png', value: 92},
        {nome: 'Rengar', imagem: '../../assets/opcoesCampeoes/Rengar_Render.png', value: 93},
        {nome: 'Riven', imagem: '../../assets/opcoesCampeoes/Riven_Render.png', value: 94},
        {nome: 'Rumble', imagem: '../../assets/opcoesCampeoes/Rumble_Render.png', value: 95},
        {nome: 'Ryze', imagem: '../../assets/opcoesCampeoes/Ryze_Render.png', value: 96},
        {nome: 'Sejuani', imagem: '../../assets/opcoesCampeoes/Sejuani_Render.png', value: 97},
        {nome: 'Shaco', imagem: '../../assets/opcoesCampeoes/Shaco_Render.png', value: 98},
        {nome: 'Shen', imagem: '../../assets/opcoesCampeoes/Shen_Render.png', value: 99},
        {nome: 'Shyvana', imagem: '../../assets/opcoesCampeoes/Shyvana_Render.png', value: 100},
        {nome: 'Singed', imagem: '../../assets/opcoesCampeoes/Singed_Render.png', value: 101},
        {nome: 'Sion', imagem: '../../assets/opcoesCampeoes/Sion_Render.png', value: 102},
        {nome: 'Sivir', imagem: '../../assets/opcoesCampeoes/Sivir_Render.png', value: 103},
        {nome: 'Skarner', imagem: '../../assets/opcoesCampeoes/Skarner_Render.png', value: 104},
        {nome: 'Sona', imagem: '../../assets/opcoesCampeoes/Sona_Render.png', value: 105},
        {nome: 'Soraka', imagem: '../../assets/opcoesCampeoes/Soraka_Render.png', value: 106},
        {nome: 'Swain', imagem: '../../assets/opcoesCampeoes/Swain_Render.png', value: 107},
        {nome: 'Sylas', imagem: '../../assets/opcoesCampeoes/Sylas_Render.png', value: 108},
        {nome: 'Syndra', imagem: '../../assets/opcoesCampeoes/Syndra_Render.png', value: 109},
        {nome: 'Tahm Kench', imagem: '../../assets/opcoesCampeoes/Tahm_Kench_Render.png', value: 110},
        {nome: 'Taliyah', imagem: '../../assets/opcoesCampeoes/Taliyah_Render.png', value: 111},
        {nome: 'Talon', imagem: '../../assets/opcoesCampeoes/Talon_Render.png', value: 112},
        {nome: 'Taric', imagem: '../../assets/opcoesCampeoes/Taric_Render.png', value: 113},
        {nome: 'Teemo', imagem: '../../assets/opcoesCampeoes/Teemo_Render.png', value: 114},
        {nome: 'Thresh', imagem: '../../assets/opcoesCampeoes/Thresh_Render.png', value: 115},
        {nome: 'Tristana', imagem: '../../assets/opcoesCampeoes/Tristana_Render.png', value: 116},
        {nome: 'Trundle', imagem: '../../assets/opcoesCampeoes/Trundle_Render.png', value: 117},
        {nome: 'Tryndamere', imagem: '../../assets/opcoesCampeoes/Tryndamere_Render.png', value: 118},
        {nome: 'Twisted Fate', imagem: '../../assets/opcoesCampeoes/Twisted_Fate_Render.png', value: 119},
        {nome: 'Twitch', imagem: '../../assets/opcoesCampeoes/Twitch_Render.png', value: 120},
        {nome: 'Udyr', imagem: '../../assets/opcoesCampeoes/Udyr_Render.png', value: 121},
        {nome: 'Urgot', imagem: '../../assets/opcoesCampeoes/Urgot_Render.png', value: 122},
        {nome: 'Varus', imagem: '../../assets/opcoesCampeoes/Varus_Render.png', value: 123},
        {nome: 'Vayne', imagem: '../../assets/opcoesCampeoes/Vayne_Render.png', value: 124},
        {nome: 'Veigar', imagem: '../../assets/opcoesCampeoes/Veigar_Render.png', value: 125},
        {nome: "Vel'Koz", imagem: '../../assets/opcoesCampeoes/Vel%27Koz_Render.png', value: 126},
        {nome: 'Vi', imagem: '../../assets/opcoesCampeoes/Vi_Render.png', value: 127},
        {nome: 'Viktor', imagem: '../../assets/opcoesCampeoes/Viktor_Render.png', value: 128},
        {nome: 'Vladimir', imagem: '../../assets/opcoesCampeoes/Vladimir_Render.png', value: 129},
        {nome: 'Volibear', imagem: '../../assets/opcoesCampeoes/Volibear_Render.png', value: 130},
        {nome: 'Warwick', imagem: '../../assets/opcoesCampeoes/Warwick_Render.png', value: 131},
        {nome: 'Wukong', imagem: '../../assets/opcoesCampeoes/Wukong_Render.png', value: 132},
        {nome: 'Xayah', imagem: '../../assets/opcoesCampeoes/Xayah_Render.png', value: 133},
        {nome: 'Xerath', imagem: '../../assets/opcoesCampeoes/Xerath_Render.png', value: 134},
        {nome: 'Xin Zhao', imagem: '../../assets/opcoesCampeoes/Xin_Zhao_Render.png', value: 135},
        {nome: 'Yasuo', imagem: '../../assets/opcoesCampeoes/Yasuo_Render.png', value: 136},
        {nome: 'Yorick', imagem: '../../assets/opcoesCampeoes/Yorick_Render.png', value: 137},
        {nome: 'Yuumi', imagem: '../../assets/opcoesCampeoes/Yuumi_Render.png', value: 138},
        {nome: 'Zac', imagem: '../../assets/opcoesCampeoes/Zac_Render.png', value: 140},
        {nome: 'Zed', imagem: '../../assets/opcoesCampeoes/Zed_Render.png', value: 141},
        {nome: 'Ziggs', imagem: '../../assets/opcoesCampeoes/Ziggs_Render.png', value: 142},
        {nome: 'Zilean', imagem: '../../assets/opcoesCampeoes/Zilean_Render.png', value: 143},
        {nome: 'Zoe', imagem: '../../assets/opcoesCampeoes/Zoe_Render.png', value: 144},
        {nome: 'Zyra', imagem: '../../assets/opcoesCampeoes/Zyra_Render.webp', value: 145},
      ];

      obterCampeoes(){
        return CampeoesUtil.campeoes;
      }
}

